Add batch transactions method
gigwage/SynapseFI-Ruby pull request #1
Opened 2022-12-27 19:36 UTC by benmercerdev

Add batch transactions method

2023-01-06 13:44 UTC, benmercerdev commented on lib/synapse_pay_rest.rb
> +require 'synapse_pay_rest/models/transaction/batch_transaction'
good, thanks

2023-01-06 13:44 UTC, benmercerdev commented on lib/synapse_pay_rest/api/transactions.rb
> +    def create_batch(user_id:, node_id:, payload:, idempotency_key: nil)
good rename

2023-01-06 13:44 UTC, benmercerdev commented on lib/synapse_pay_rest/models/transaction/transaction.rb
> +      def payload_for_create(node:, to_type:, to_id:, amount:, currency:, ip:, **options)
Curious about the reasoning to pull this out of the `PayloadCreator` and add this back in here? Both the BatchTransaction and Transaction classes will need to use the same function

2023-01-06 13:54 UTC, benmercerdev commented on lib/synapse_pay_rest/models/transaction/batch_transaction.rb
> +          'transactions' => transactions.map{|transaction| payload_for_create(transaction)}
@hendragunz I see you renamed this method back to `payload_for_create` and removed the `PayloadCreator` import -- the reason behind the `PayloadCreator` was to share the `payload_for_single_transaction` function in both the `Transaction` and `BatchTransaction` classes

2023-01-13 21:16 UTC, carltonsmith requested changes
Aside from the file that looks like it should be removed, this looks good

2023-01-13 21:16 UTC, carltonsmith commented on lib/synapse_pay_rest/models/batch_transactions.bak/batch_trans.rb
> +# module SynapsePayRest
Seems like this file should be deleted?

2023-01-17 07:13 UTC, hendragunz commented on lib/synapse_pay_rest/models/batch_transactions.bak/batch_trans.rb
> +# module SynapsePayRest
Oh.. yeah I missed that

2023-01-30 21:44 UTC, carltonsmith approved these changes

2023-01-31 04:55 UTC, hendragunz commented
@carltonsmith @benmercerdev  just info.. actually this PR can be ignored. 
Because those all changes are embedded directly in GigWage application. 

I put it into `lib/synapse_pay_rest/monkey_pathces`. 
You can check there

2023-03-01 16:17 UTC, carltonsmith commented
@hendragunz We are in the midst of moving all of the monkey patch changes into the gem, so I would rather we have it here instead

2023-03-08 05:06 UTC, hendragunz commented
> @hendragunz We are in the midst of moving all of the monkey patch changes into the gem, so I would rather we have it here instead

will move those codes into SynapsePayRest gem instead @carltonsmith

2023-03-21 13:34 UTC, merged